# Sidebar navigation

- label: "Get Started"
  link: "/"
- label: "Resources"
  link: "/resources"
- label: Algorithms
  items:
    - label: "Arrays"
      link: "/algorithms/arrays"
    - label: "Strings"
      link: "/algorithms/strings"
    - label: "Sorts"
      link: "/algorithms/sorts"
    - label: "Searches"
      link: "/algorithms/searches"
    - label: "Math"
      link: "/algorithms/math"
    - label: "Other"
      link: "/algorithms/other"
- label: Data Structures
  items:
    - label: "Stacks"
      link: "/data-structures/stacks"
    - label: "Queues"
      link: "/data-structures/queues"
    - label: "Hash Tables"
      link: "/data-structures/hash-tables"
    - label: "Heaps"
      link: "/data-structures/heaps"
    - label: "Trees"
      link: "/data-structures/trees"
    - label: "Tries"
      link: "/data-structures/tries"
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: "Github"
      link: https://github.com/WilderDev/Algo-DS_docs
