# Sidebar navigation

- label: "Get Started"
  link: "/"
- label: "Resources"
  link: "/resources"
- label: Algorithms
  items:
    - label: "Arrays"
      link: "/algorithms/arrays"
    - label: "Strings"
      link: "/algorithms/strings"
    - label: "Sorts"
      link: "/algorithms/sorts"
    - label: "Searches"
      link: "/algorithms/searches"
    - label: "Math"
      link: "/algorithms/math"
- label: Data Structures
  items:
    - label: "Linked-Lists"
      link: "/data-structures/linked-lists"
    - label: "Stacks & Queues"
      link: "/data-structures/stacks-and-queues"
    - label: "Graphs"
      link: "/data-structures/graphs"
    - label: "Hash Tables"
      link: "/data-structures/hash-tables"
    - label: "Heaps"
      link: "/data-structures/heaps"
    - label: "Trees"
      link: "/data-structures/trees"
    - label: "Tries"
      link: "/data-structures/tries"
- label: More
  items:
    - label: Algorithm Analysis
      link: /bigO
    - label: FAQ
      link: /faq
    - label: "Github"
      link: https://github.com/WilderDev/Algo-DS_docs
