# Sidebar navigation

- label: "Get Started"
  link: "/"
- label: Algorithms
  items:
    - label: "Sorts"
      link: "/algorithms/sorts"
    - label: "Searches"
      link: "/algorithms/searches"
    - label: "Arrays"
      link: "/algorithms/arrays"
    - label: "Strings"
      link: "/algorithms/strings"
    - label: "Math"
      link: "/algorithms/math"
- label: Data Structures
  items:
    - label: "Linked-Lists"
      link: "/data-structures/linked-lists"
    - label: "Stacks & Queues"
      link: "/data-structures/stacks-and-queues"
    - label: "Graphs"
      link: "/data-structures/graphs"
    - label: "Hash Tables"
      link: "/data-structures/hash-tables"
    - label: "Trees"
      link: "/data-structures/trees"
- label: More
  items:
    - label: Algorithm Analysis
      link: /bigO
    - label: Resources
      link: /resources
