# Sidebar navigation

- label: "Get Started"
  link: "/"
- label: "Resources"
  link: "/resources"
- label: Algorithms
  items:
    - label: "Arrays"
      link: "/algorithms/arrays"
    - label: "Strings"
      link: "/algorithms/strings"
    - label: "Sorts"
      link: "/algorithms/sorts"
    - label: "Searches"
      link: "/algorithms/searches"
    - label: "Math"
      link: "/algorithms/math"
    - label: "Other"
      link: "/algorithms/other"
- label: Data Structures
  items:
    - label: "Graphs"
      link: "/data-structures/graphs"
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: "Github"
      link: https://github.com/WilderDev/Algo-DS_docs
